//
//  BETheme.swift
//  budget-expense
//
//  Created by Matteo Comisso on 15/10/16.
//  Copyright © 2016 mcomisso. All rights reserved.
//

import Foundation
import Material

struct BETheme {
    struct Colors {
        static let darkPrimary = Color.teal.darken1
        static let primary = Color.teal.base
        static let lightPrimary = Color.teal.lighten1
        static let textIcons = Color.grey.lighten5
        static let accent = Color.red.base
        static let primaryText = Color.darkText.primary
        static let secondaryText = Color.darkText.secondary
        static let divider = Color.grey.lighten1

        static let income = Color.teal.base
        static let expense = Color.red.base
    }

}


/*
 
 /* Palette generated by Material Palette - materialpalette.com/teal/red */

 .dark-primary-color    { background: #00796B; }
 .default-primary-color { background: #009688; }
 .light-primary-color   { background: #B2DFDB; }
 .text-primary-color    { color: #FFFFFF; }
 .accent-color          { background: #FF5252; }
 .primary-text-color    { color: #212121; }
 .secondary-text-color  { color: #757575; }
 .divider-color         { border-color: #BDBDBD; }

 */
