//
//  BETheme.swift
//  budget-expense
//
//  Created by Matteo Comisso on 15/10/16.
//  Copyright © 2016 mcomisso. All rights reserved.
//

import Foundation

struct BETheme {
    struct Colors {
        static let darkPrimaryColor = ""
        static let primaryColor = ""
        static let lightPrimaryColor = ""
        static let textIcons = ""
        static let accentColor = ""
        static let primaryText = ""
        static let secondaryText = ""
        static let dividerColor = ""
    }
}


/*
 
 /* Palette generated by Material Palette - materialpalette.com/teal/red */

 .dark-primary-color    { background: #00796B; }
 .default-primary-color { background: #009688; }
 .light-primary-color   { background: #B2DFDB; }
 .text-primary-color    { color: #FFFFFF; }
 .accent-color          { background: #FF5252; }
 .primary-text-color    { color: #212121; }
 .secondary-text-color  { color: #757575; }
 .divider-color         { border-color: #BDBDBD; }

 */

public extension UIColor {

    /**
     Initialize a UIColor from the single RGB values.

     - parameter red:   Red color value
     - parameter green: Green color value
     - parameter blue:  Blue color value

     - returns: An UIColor with the specified values
     */
    convenience init(red: Int, green: Int, blue: Int) {
        assert(red >= 0 && red <= 255, "Invalid red component")
        assert(green >= 0 && green <= 255, "Invalid green component")
        assert(blue >= 0 && blue <= 255, "Invalid blue component")

        self.init(red: CGFloat(red) / 255.0, green: CGFloat(green) / 255.0, blue: CGFloat(blue) / 255.0, alpha: 1.0)
    }

    //    convenience init(netHex:Int) {
    //        self.init(red:(netHex >> 16) & 0xff, green:(netHex > > 8) & 0xff, blue:netHex & 0xff)
    //    }

    /**
     Initialize a UIColor from the single hex value.

     - parameter hexColor: Hex value
     - parameter alpha:    Alpha value

     - returns: An UIColor from the specified values
     */
    convenience init (hexColor:String, alpha:CGFloat = 1.0) {

        var cString:String = hexColor.stringByTrimmingCharactersInSet(NSCharacterSet.whitespaceAndNewlineCharacterSet()).uppercaseString
        var r:CUnsignedInt = 0, g:CUnsignedInt = 0, b:CUnsignedInt = 0;

        if (cString.hasPrefix("#")) {
            cString = (cString as NSString).substringFromIndex(1)
        }

        if (cString.characters.count == 6) {
            let rString = (cString as NSString).substringToIndex(2)
            let gString = ((cString as NSString).substringFromIndex(2) as NSString).substringToIndex(2)
            let bString = ((cString as NSString).substringFromIndex(4) as NSString).substringToIndex(2)

            NSScanner(string: rString).scanHexInt(&r)
            NSScanner(string: gString).scanHexInt(&g)
            NSScanner(string: bString).scanHexInt(&b)
        }

        self.init(red: CGFloat(r) / 255.0, green: CGFloat(g) / 255.0, blue: CGFloat(b) / 255.0, alpha: alpha)
    }
}
