//
//  BETheme.swift
//  budget-expense
//
//  Created by Matteo Comisso on 15/10/16.
//  Copyright © 2016 mcomisso. All rights reserved.
//

import Foundation

struct BETheme {
    struct Colors {
        static let darkPrimaryColor = ""
        static let primaryColor = ""
        static let lightPrimaryColor = ""
        static let textIcons = ""
        static let accentColor = ""
        static let primaryText = ""
        static let secondaryText = ""
        static let dividerColor = ""
    }
}


/*
 
 /* Palette generated by Material Palette - materialpalette.com/teal/red */

 .dark-primary-color    { background: #00796B; }
 .default-primary-color { background: #009688; }
 .light-primary-color   { background: #B2DFDB; }
 .text-primary-color    { color: #FFFFFF; }
 .accent-color          { background: #FF5252; }
 .primary-text-color    { color: #212121; }
 .secondary-text-color  { color: #757575; }
 .divider-color         { border-color: #BDBDBD; }

 */
